### ISSUE TITLE
Paradiso error with versions newer than 0.2.0

### ISSUE THREAD

**Issue by Patrick-Cole** [simpeg/pymatsolver#52]
I install using pip on windows. Up to version 0.2.0, I did not get any errors when running simpeg TDEM inversion. Now it complains about needing pydiso. My problem is that the pip install of pydiso needs compilers and other libraries. Can something be done so that the new versions behave like 0.2.0?

**Comment by jcapriot** [comment]
If you need 0.2 behavior, I’d recommend installing 0.2.

If you need 0.3, then your current options are:
 * install pydiso (which as you’ve noticed is not as easy as pip install because it needs compilers and other libraries). However installing `pymatsolver` through conda-forge will install `pydiso` for you if you’re on an intel machine. 
 
 or:
* Use the most recent main branch of SimPEG at https://github.com/simpeg/simpeg. It has been updated to support the changes. A new release version of SimPEG will likely be out in a week.

**Comment by Patrick-Cole** [comment]
Thanks for the feedback. I will use 0.2 for now and wait for the new SimPEG.
